const PDFDocument = require("pdfkit");

// Brand colors
const BRAND = { r: 26, g: 140, b: 255 }; // #1A8CFF — KingsChat Blue
const DARK = { r: 28, g: 25, b: 23 };
const GRAY = { r: 107, g: 107, b: 107 };
const LIGHT_BG = { r: 249, g: 247, b: 245 };

/**
 * Generate a professional PDF from a proposal JSON object.
 * Returns a readable stream.
 */
function generateProposalPDF(proposal, meta = {}) {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 60, bottom: 60, left: 55, right: 55 },
    info: {
      Title: proposal.title || "Event Proposal",
      Author: meta.author || "Prime Ops",
      Subject: proposal.subtitle || "Event Proposal",
    },
  });

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // ── Helper functions ────────────────────────────────────────────
  function drawLine(y, color = BRAND) {
    doc.save()
      .moveTo(doc.page.margins.left, y)
      .lineTo(doc.page.width - doc.page.margins.right, y)
      .strokeColor([color.r, color.g, color.b])
      .lineWidth(1.5)
      .stroke()
      .restore();
  }

  function sectionTitle(text) {
    checkPageBreak(40);
    doc.moveDown(0.8);
    doc.fontSize(13).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica-Bold")
      .text(text.toUpperCase(), { continued: false });
    const y = doc.y + 2;
    drawLine(y);
    doc.moveDown(0.6);
    doc.fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica").fontSize(10);
  }

  function bodyText(text) {
    checkPageBreak(20);
    doc.fontSize(10).fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica")
      .text(text, { lineGap: 3 });
  }

  function bulletItem(text) {
    checkPageBreak(20);
    doc.fontSize(10).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica")
      .text("●  ", { continued: true })
      .fillColor([DARK.r, DARK.g, DARK.b])
      .text(text, { lineGap: 3 });
  }

  function grayLabel(label, value) {
    checkPageBreak(18);
    doc.fontSize(9).fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica-Bold")
      .text(`${label}: `, { continued: true })
      .font("Helvetica").fillColor([DARK.r, DARK.g, DARK.b])
      .text(value || "—");
  }

  function checkPageBreak(needed) {
    if (doc.y + needed > doc.page.height - doc.page.margins.bottom - 30) {
      doc.addPage();
      doc.y = doc.page.margins.top;
    }
  }

  // ── COVER / HEADER ──────────────────────────────────────────────
  // Brand bar
  doc.save()
    .rect(0, 0, doc.page.width, 6)
    .fill([BRAND.r, BRAND.g, BRAND.b])
    .restore();

  doc.moveDown(1.5);

  // Title
  doc.fontSize(24).fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica-Bold")
    .text(proposal.title || "Event Proposal", { align: "left" });

  if (proposal.subtitle) {
    doc.fontSize(12).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica")
      .text(proposal.subtitle, { align: "left" });
  }

  doc.moveDown(0.3);
  drawLine(doc.y);
  doc.moveDown(0.5);

  // Meta info row
  if (meta.committeeName) grayLabel("Committee", meta.committeeName);
  if (meta.eventTitle) grayLabel("Event", meta.eventTitle);
  if (meta.submittedBy) grayLabel("Prepared by", meta.submittedBy);
  grayLabel("Date", new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  grayLabel("Generated by", "Prime Ops AI");

  // ── SUMMARY ─────────────────────────────────────────────────────
  if (proposal.summary) {
    sectionTitle("Executive Summary");
    bodyText(proposal.summary);
  }

  // ── OBJECTIVES ──────────────────────────────────────────────────
  if (proposal.objectives?.length > 0) {
    sectionTitle("Objectives");
    proposal.objectives.forEach((obj) => bulletItem(typeof obj === "string" ? obj : obj.text || obj));
  }

  // ── TARGET AUDIENCE ─────────────────────────────────────────────
  if (proposal.targetAudience) {
    sectionTitle("Target Audience");
    const ta = proposal.targetAudience;
    if (ta.description) bodyText(ta.description);
    if (ta.estimatedAttendance) {
      doc.moveDown(0.3);
      grayLabel("Estimated Attendance", String(ta.estimatedAttendance));
    }
    if (ta.demographics?.length > 0) {
      doc.moveDown(0.3);
      ta.demographics.forEach((d) => bulletItem(d));
    }
  }

  // ── DATE & VENUE ────────────────────────────────────────────────
  if (proposal.dateRecommendation || proposal.venue) {
    sectionTitle("Date & Venue");
    if (proposal.dateRecommendation) {
      const dr = proposal.dateRecommendation;
      if (dr.suggestedTimeframe) grayLabel("Suggested Date", dr.suggestedTimeframe);
      if (dr.duration) grayLabel("Duration", dr.duration);
      if (dr.rationale) { doc.moveDown(0.2); bodyText(dr.rationale); }
    }
    if (proposal.venue) {
      doc.moveDown(0.3);
      const v = proposal.venue;
      if (v.type) grayLabel("Venue Type", v.type);
      if (v.requirements?.length > 0) {
        v.requirements.forEach((r) => bulletItem(r));
      }
      if (v.suggestions?.length > 0) {
        grayLabel("Suggestions", v.suggestions.join(", "));
      }
    }
  }

  // ── AGENDA ──────────────────────────────────────────────────────
  if (proposal.agenda?.length > 0) {
    sectionTitle("Agenda");
    proposal.agenda.forEach((day) => {
      checkPageBreak(30);
      doc.fontSize(11).fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica-Bold")
        .text(day.day || day.title || "Schedule");
      doc.moveDown(0.3);

      (day.sessions || day.items || []).forEach((s) => {
        checkPageBreak(25);
        doc.fontSize(9).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica-Bold")
          .text(s.time || "", { continued: true, width: 80 })
          .fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica-Bold")
          .text(`  ${s.title || s.activity || ""}`)
          .font("Helvetica").fontSize(9).fillColor([GRAY.r, GRAY.g, GRAY.b]);
        if (s.description) doc.text(`     ${s.description}`);
        doc.moveDown(0.2);
      });
      doc.moveDown(0.3);
    });
  }

  // ── BUDGET ──────────────────────────────────────────────────────
  if (proposal.budget) {
    sectionTitle("Budget");
    const b = proposal.budget;
    if (b.estimatedTotal) {
      doc.fontSize(14).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica-Bold")
        .text(b.estimatedTotal);
      doc.moveDown(0.4);
    }

    if (b.breakdown?.length > 0) {
      // Table header
      checkPageBreak(30);
      const colW = [pageWidth * 0.35, pageWidth * 0.25, pageWidth * 0.4];
      const startX = doc.page.margins.left;
      let tableY = doc.y;

      doc.save().rect(startX, tableY, pageWidth, 18).fill([LIGHT_BG.r, LIGHT_BG.g, LIGHT_BG.b]).restore();
      doc.fontSize(8).fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica-Bold");
      doc.text("CATEGORY", startX + 5, tableY + 5, { width: colW[0] });
      doc.text("ESTIMATE", startX + colW[0] + 5, tableY + 5, { width: colW[1] });
      doc.text("NOTES", startX + colW[0] + colW[1] + 5, tableY + 5, { width: colW[2] });
      tableY += 20;

      doc.fontSize(9).font("Helvetica").fillColor([DARK.r, DARK.g, DARK.b]);
      b.breakdown.forEach((item, i) => {
        checkPageBreak(20);
        tableY = doc.y;
        if (i % 2 === 0) {
          doc.save().rect(startX, tableY, pageWidth, 16).fill([252, 251, 250]).restore();
        }
        doc.fillColor([DARK.r, DARK.g, DARK.b]).fontSize(9);
        doc.text(item.category || "", startX + 5, tableY + 4, { width: colW[0] });
        doc.text(item.estimate || item.amount || "", startX + colW[0] + 5, tableY + 4, { width: colW[1] });
        doc.text(item.notes || "", startX + colW[0] + colW[1] + 5, tableY + 4, { width: colW[2] });
        doc.y = tableY + 18;
      });
    }
  }

  // ── COMMITTEES / TEAMS ──────────────────────────────────────────
  if (proposal.committees?.length > 0) {
    sectionTitle("Committees & Teams");
    proposal.committees.forEach((c) => {
      checkPageBreak(30);
      doc.fontSize(11).fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica-Bold")
        .text(c.name);
      if (c.suggestedSize) {
        doc.fontSize(9).fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica")
          .text(c.suggestedSize);
      }
      if (c.responsibilities?.length > 0) {
        c.responsibilities.forEach((r) => bulletItem(typeof r === "string" ? r : r.text || r));
      }
      doc.moveDown(0.4);
    });
  }

  // ── TIMELINE ────────────────────────────────────────────────────
  if (proposal.timeline?.length > 0) {
    sectionTitle("Timeline");
    proposal.timeline.forEach((phase) => {
      checkPageBreak(30);
      doc.fontSize(10).fillColor([BRAND.r, BRAND.g, BRAND.b]).font("Helvetica-Bold")
        .text(phase.phase || phase.title || "", { continued: true })
        .fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica")
        .text(`  ${phase.timeframe || phase.date || ""}`);
      if (phase.tasks?.length > 0) {
        phase.tasks.forEach((t) => bulletItem(typeof t === "string" ? t : t.text || t));
      }
      doc.moveDown(0.3);
    });
  }

  // ── RISKS ───────────────────────────────────────────────────────
  if (proposal.risks?.length > 0) {
    sectionTitle("Risks & Mitigation");
    proposal.risks.forEach((r) => {
      checkPageBreak(25);
      doc.fontSize(10).fillColor([DARK.r, DARK.g, DARK.b]).font("Helvetica-Bold")
        .text(`⚠ ${r.risk || r.title || ""}`);
      if (r.mitigation) {
        doc.fontSize(9).fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica")
          .text(`Mitigation: ${r.mitigation}`);
      }
      doc.moveDown(0.3);
    });
  }

  // ── SUCCESS METRICS ─────────────────────────────────────────────
  if (proposal.successMetrics?.length > 0) {
    sectionTitle("Success Metrics");
    proposal.successMetrics.forEach((m) => bulletItem(typeof m === "string" ? m : m.text || m));
  }

  // ── FOOTER on every page ────────────────────────────────────────
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(7).fillColor([GRAY.r, GRAY.g, GRAY.b]).font("Helvetica")
      .text(
        `Prime Ops — ${proposal.title || "Proposal"} — Page ${i + 1} of ${range.count}`,
        doc.page.margins.left,
        doc.page.height - 35,
        { align: "center", width: pageWidth }
      );
    // Bottom brand bar
    doc.save()
      .rect(0, doc.page.height - 6, doc.page.width, 6)
      .fill([BRAND.r, BRAND.g, BRAND.b])
      .restore();
  }

  doc.end();
  return doc;
}

module.exports = { generateProposalPDF };
