"use client";

import { useState, useEffect, useCallback } from "react";
import { useAuth } from "../../lib/auth";
import StatusUpdateTimeline from "../../components/StatusUpdateTimeline";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/api";

// ─── Consolidated Report Display ───────────────────────────────────
function ConsolidatedReport({ report, onClose }) {
  if (!report) return null;

  const statusColors = {
    on_track: "bg-green-100 text-green-700",
    ahead: "bg-blue-100 text-blue-700",
    at_risk: "bg-orange-100 text-orange-700",
    behind: "bg-red-100 text-red-700",
  };

  return (
    <div className="bg-white rounded-2xl border border-surface-200 shadow-lg overflow-hidden animate-fade-in">
      {/* Header */}
      <div className="bg-gradient-to-r from-brand-500 to-brand-600 px-6 py-5 text-white">
        <div className="flex items-start justify-between">
          <div>
            <h2 className="font-display text-xl">{report.title}</h2>
            <p className="text-brand-100 text-sm mt-1">
              {report.date} · {report.committeeCount} committees reporting
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                const lines = [
                  report.title || "Consolidated Status Report",
                  "=".repeat(60),
                  `Date: ${report.date}`,
                  `Committees: ${report.committeeCount}`,
                  `Overall Progress: ${report.overallProgress}%`,
                  `Status: ${(report.statusLevel || "").replace("_", " ")}`,
                  "",
                  "EXECUTIVE SUMMARY",
                  "-".repeat(40),
                  report.executiveSummary || "N/A",
                  "",
                ];
                if (report.committeeBreakdown?.length > 0) {
                  lines.push("COMMITTEE BREAKDOWN", "-".repeat(40));
                  report.committeeBreakdown.forEach((c) => {
                    lines.push(`  [${c.progress}%] ${c.name} — ${(c.status || "").replace("_", " ")}`);
                    if (c.highlight) lines.push(`        ${c.highlight}`);
                  });
                  lines.push("");
                }
                if (report.consolidatedMetrics?.length > 0) {
                  lines.push("KEY METRICS", "-".repeat(40));
                  report.consolidatedMetrics.forEach((m) => {
                    lines.push(`  ${m.label}: ${m.value}${m.target ? ` (Target: ${m.target})` : ""}`);
                  });
                  lines.push("");
                }
                if (report.keyAccomplishments?.length > 0) {
                  lines.push("KEY ACCOMPLISHMENTS", "-".repeat(40));
                  report.keyAccomplishments.forEach((a) => lines.push(`  ✓ ${a}`));
                  lines.push("");
                }
                if (report.criticalIssues?.length > 0) {
                  lines.push("CRITICAL ISSUES", "-".repeat(40));
                  report.criticalIssues.forEach((c) => lines.push(`  ⚠ ${c}`));
                  lines.push("");
                }
                if (report.upcomingMilestones?.length > 0) {
                  lines.push("UPCOMING MILESTONES", "-".repeat(40));
                  report.upcomingMilestones.forEach((m) => lines.push(`  → ${m}`));
                  lines.push("");
                }
                if (report.recommendations?.length > 0) {
                  lines.push("RECOMMENDATIONS", "-".repeat(40));
                  report.recommendations.forEach((r) => lines.push(`  💡 ${r}`));
                  lines.push("");
                }
                lines.push("=".repeat(60), "Generated by Prime Ops AI");
                const blob = new Blob([lines.join("\n")], { type: "text/plain" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = `consolidated-report-${new Date().toISOString().slice(0, 10)}.txt`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="flex items-center gap-1.5 text-xs text-white/80 hover:text-white bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-lg font-medium transition-all"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" x2="12" y1="15" y2="3" />
              </svg>
              Download
            </button>
            <button onClick={onClose} className="text-white/70 hover:text-white transition-colors">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
            </button>
          </div>
        </div>
        {/* Overall progress */}
        <div className="mt-4 flex items-center gap-4">
          <div className="relative w-16 h-16">
            <svg className="w-16 h-16 -rotate-90" viewBox="0 0 36 36">
              <circle cx="18" cy="18" r="15" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="3" />
              <circle cx="18" cy="18" r="15" fill="none" stroke="white" strokeWidth="3"
                strokeDasharray={`${(report.overallProgress / 100) * 94.2} 94.2`} strokeLinecap="round" />
            </svg>
            <span className="absolute inset-0 flex items-center justify-center text-lg font-bold">{report.overallProgress}%</span>
          </div>
          <div>
            <span className={`text-xs px-2.5 py-1 rounded-full font-medium ${statusColors[report.statusLevel] || ""}`}>
              {(report.statusLevel || "").replace("_", " ")}
            </span>
            <p className="text-sm text-brand-100 mt-1">Overall Event Readiness</p>
          </div>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Executive Summary */}
        <div>
          <h3 className="font-display text-base text-surface-900 mb-2">Executive Summary</h3>
          <p className="text-sm text-surface-600 leading-relaxed">{report.executiveSummary}</p>
        </div>

        {/* Committee Breakdown */}
        {report.committeeBreakdown?.length > 0 && (
          <div>
            <h3 className="font-display text-base text-surface-900 mb-3">Committee Breakdown</h3>
            <div className="space-y-2">
              {report.committeeBreakdown.map((c, i) => (
                <div key={i} className="flex items-center gap-3 p-3 bg-surface-50 rounded-lg">
                  <div className="w-10 h-10 rounded-full bg-white border border-surface-200 flex items-center justify-center flex-shrink-0">
                    <span className="text-sm font-bold text-surface-900">{c.progress}%</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium text-surface-900">{c.name}</p>
                      <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${statusColors[c.status] || "bg-gray-100"}`}>
                        {(c.status || "").replace("_", " ")}
                      </span>
                    </div>
                    <p className="text-xs text-surface-500 mt-0.5">{c.highlight}</p>
                  </div>
                  <div className="w-24 h-2 bg-surface-200 rounded-full overflow-hidden flex-shrink-0">
                    <div className="h-full bg-brand-500 rounded-full" style={{ width: `${c.progress}%` }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Metrics */}
        {report.consolidatedMetrics?.length > 0 && (
          <div>
            <h3 className="font-display text-base text-surface-900 mb-3">Key Metrics</h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              {report.consolidatedMetrics.map((m, i) => (
                <div key={i} className="bg-surface-50 rounded-lg p-3 border border-surface-100">
                  <p className="text-[10px] text-surface-400 uppercase tracking-wider">{m.label}</p>
                  <p className="text-lg font-bold text-surface-900 mt-0.5">{m.value}</p>
                  {m.target && <p className="text-[10px] text-surface-400">Target: {m.target}</p>}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Accomplishments + Critical Issues side by side */}
        <div className="grid grid-cols-2 gap-4">
          {report.keyAccomplishments?.length > 0 && (
            <div>
              <h3 className="font-display text-sm text-surface-900 mb-2">Key Accomplishments</h3>
              <div className="space-y-1.5">
                {report.keyAccomplishments.map((a, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-surface-700">
                    <span className="text-green-500 mt-0.5 flex-shrink-0">✓</span><span>{a}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
          {report.criticalIssues?.length > 0 && (
            <div>
              <h3 className="font-display text-sm text-red-700 mb-2">Critical Issues</h3>
              <div className="space-y-1.5">
                {report.criticalIssues.map((c, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-red-700">
                    <span className="text-red-500 mt-0.5 flex-shrink-0">⚠</span><span>{c}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Upcoming Milestones */}
        {report.upcomingMilestones?.length > 0 && (
          <div>
            <h3 className="font-display text-sm text-surface-900 mb-2">Upcoming Milestones</h3>
            <div className="space-y-1.5">
              {report.upcomingMilestones.map((m, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-surface-600">
                  <span className="text-blue-500 mt-0.5 flex-shrink-0">→</span><span>{m}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {report.recommendations?.length > 0 && (
          <div className="bg-purple-50 border border-purple-100 rounded-xl p-4">
            <h3 className="font-display text-sm text-purple-900 mb-2 flex items-center gap-2">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83" />
              </svg>
              Recommendations
            </h3>
            <div className="space-y-1.5">
              {report.recommendations.map((r, i) => (
                <div key={i} className="flex items-start gap-2 text-xs text-purple-800">
                  <span className="text-purple-500 mt-0.5 flex-shrink-0">💡</span><span>{r}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════
// MAIN STATUS UPDATES PAGE
// ═══════════════════════════════════════════════════════════════════════

export default function StatusUpdatesPage() {
  const { authFetch } = useAuth();
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [consolidating, setConsolidating] = useState(null); // eventId being consolidated
  const [report, setReport] = useState(null);

  const fetchEvents = useCallback(async () => {
    try {
      const res = await fetch(`${API}/events`);
      const data = await res.json();
      // Only events that have committees
      setEvents((data.events || []).filter((e) => e.committees?.length > 0));
      if (!selectedEvent && data.events?.length > 0) {
        const first = data.events.find((e) => e.committees?.length > 0);
        if (first) setSelectedEvent(first.id);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [selectedEvent]);

  useEffect(() => { fetchEvents(); }, [fetchEvents]);

  async function handleConsolidate(eventId) {
    setConsolidating(eventId);
    setReport(null);
    try {
      const data = await authFetch("/status-updates/consolidate", {
        method: "POST",
        body: JSON.stringify({ eventId }),
      });
      setReport(data.report);
    } catch (err) {
      alert("Failed to consolidate: " + err.message);
    } finally {
      setConsolidating(null);
    }
  }

  const currentEvent = events.find((e) => e.id === selectedEvent);

  if (loading) {
    return (
      <main className="min-h-screen bg-surface-50 p-8 flex items-center justify-center">
        <div className="w-6 h-6 border-2 border-brand-500 border-t-transparent rounded-full animate-spin" />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-surface-50">
      <div className="max-w-5xl mx-auto px-8 py-8 space-y-6">
        {/* Page header */}
        <div>
          <h1 className="font-display text-2xl text-surface-900">Status Updates</h1>
          <p className="text-surface-500 text-sm mt-1">
            View all committee progress reports and generate consolidated project-wide summaries.
          </p>
        </div>

        {/* Event selector */}
        {events.length > 0 ? (
          <div className="flex items-center gap-3 flex-wrap">
            {events.map((ev) => (
              <button
                key={ev.id}
                onClick={() => { setSelectedEvent(ev.id); setReport(null); }}
                className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                  selectedEvent === ev.id
                    ? "bg-brand-500 text-white shadow-sm"
                    : "bg-white text-surface-600 border border-surface-200 hover:border-brand-300"
                }`}
              >
                {ev.title}
                <span className="ml-1.5 text-xs opacity-70">({ev.committees?.length || 0})</span>
              </button>
            ))}
          </div>
        ) : (
          <div className="bg-white rounded-xl border border-surface-200 p-10 text-center">
            <p className="text-surface-400">No events with committees found.</p>
          </div>
        )}

        {/* Selected event content */}
        {selectedEvent && (
          <>
            {/* Consolidate button */}
            <div className="flex items-center justify-between bg-white rounded-xl border border-surface-200 p-4">
              <div>
                <h2 className="font-display text-lg text-surface-900">{currentEvent?.title}</h2>
                <p className="text-xs text-surface-400 mt-0.5">
                  {currentEvent?.committees?.length || 0} committees
                </p>
              </div>
              <button
                onClick={() => handleConsolidate(selectedEvent)}
                disabled={consolidating === selectedEvent}
                className="bg-gradient-to-r from-brand-500 to-brand-600 hover:from-brand-600 hover:to-brand-700 disabled:from-surface-300 disabled:to-surface-300 text-white font-medium px-5 py-2.5 rounded-xl transition-all flex items-center gap-2 shadow-sm"
              >
                {consolidating === selectedEvent ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Prime Ops is consolidating...
                  </>
                ) : (
                  <>
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83" />
                    </svg>
                    Consolidate All Updates
                  </>
                )}
              </button>
            </div>

            {/* Consolidated report */}
            {report && <ConsolidatedReport report={report} onClose={() => setReport(null)} />}

            {/* Individual updates */}
            <div>
              <h3 className="font-display text-base text-surface-900 mb-4">Individual Committee Updates</h3>
              <StatusUpdateTimeline eventId={selectedEvent} isDirector />
            </div>
          </>
        )}
      </div>
    </main>
  );
}
